language: go
go:
  - 1.x
os:
  - linux
sudo: required
before_install:
  - sudo apt install openvswitch-switch
  - sudo ovs-vsctl add-br ovsbr0
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -d ./...
script:
  - ./scripts/licensecheck.sh
  - go build -tags=gofuzz ./...
  - go vet ./...
  - staticcheck ./...
  - ./scripts/gofmt.sh
  - ./scripts/golint.sh
  - go test -race ./...
  - go test -c -race ./ovsdb
  - sudo ./ovsdb.test -test.v