language: go
go:
  - 1.12
os:
  - linux
sudo: required
before_install:
  - sudo apt update
  - sudo apt install openvswitch-switch
  - sudo ovs-vsctl add-br ovsbr0
  - go get -u golang.org/x/lint/golint
  - go get -d ./...
script:
  - ./scripts/licensecheck.sh
  - go build -tags=gofuzz ./...
  - go vet ./...
  - ./scripts/gofmt.sh
  - ./scripts/golint.sh
  - go test -race ./...
  - go test -c -race ./ovsdb
  - sudo ./ovsdb.test -test.v
